### ISSUE TITLE
LightGBM install fails on mac

### ISSUE THREAD

**Issue by ejm714** [drivendataorg/cyfi#114]
To reproduce
```
❯ pip install cyfi
❯ cyfi predict --help
Traceback (most recent call last):
  File "/Users/emily/opt/anaconda3/envs/cyfi/bin/cyfi", line 5, in <module>
    from cyfi.cli import app
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/cyfi/cli.py", line 12, in <module>
    from cyfi.pipeline import CyFiPipeline
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/cyfi/pipeline.py", line 7, in <module>
    import lightgbm as lgb
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/lightgbm/basic.py", line 226, in <module>
    _LIB = _load_lib()
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/lightgbm/basic.py", line 211, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/lightgbm/lib/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/emily/opt/anaconda3/envs/cyfi/lib/python3.10/site-packages/lightgbm/lib/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)
```

**Comment by jayqi** [comment]
@ejm714 this seems to suggest you're missing a system library libomp. Have you tried `brew install libomp`? 

https://formulae.brew.sh/formula/libomp

**Comment by jayqi** [comment]
It's interesting actually that you are able to install lightgbm but then it errors at runtime. There are lots of other reports about errors at installation time related to libomp with compiling lightgbm. 

https://github.com/microsoft/LightGBM/issues/5700

**Comment by ejm714** [comment]
> Have you tried brew install libomp?

Yes and I get the same error. I think the best option for supporting Apple silicon will be with conda-forge.

**Comment by jayqi** [comment]
For future reference, this SO post has a lot of answers that do a good job explaining the basic mechanics of the underlying problem: https://stackoverflow.com/questions/61971851/getting-this-simple-problem-while-importing-xgboost-on-jupyter-notebook

---

In any case, I got [repro-zipfile on conda-forge](https://github.com/conda-forge/repro-zipfile-feedstock) so that shouldn't be a blocker for a cyfi feedstock anymore.

**Comment by ejm714** [comment]
conda-forge PR opened here: https://github.com/conda-forge/staged-recipes/pull/24944
